"""
streamlit run live_app.py

CleanCharge Live public dashboard.

The application presents outputs generated by the CleanCharge Live
operational pipeline. It does not fetch data, train models or generate
forecasts inside Streamlit.

Run from the repository root:

    streamlit run live_app.py

Required backend outputs
------------------------
data/live/forecasts/today.csv
data/live/status/today_recommendation.json
data/live/status/forecast_status.json
data/live/scorecard/rolling_scorecard.json
data/live/scorecard/forecast_history.json
data/live/scorecard/system_status.json

Optional evaluation outputs
---------------------------
data/live/validation/YYYY-MM-DD/evaluation_summary.json
data/live/validation/YYYY-MM-DD/scientific_comparison.csv
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st


# ---------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="CleanCharge Live",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

TZ_NAME = "Australia/Melbourne"
MELBOURNE_TZ = ZoneInfo(TZ_NAME)

ROOT = Path(__file__).resolve().parent
LIVE_DIR = ROOT / "data" / "live"

FORECAST_FILE = (
    LIVE_DIR
    / "forecasts"
    / "today.csv"
)

RECOMMENDATION_FILE = (
    LIVE_DIR
    / "status"
    / "today_recommendation.json"
)

FORECAST_STATUS_FILE = (
    LIVE_DIR
    / "status"
    / "forecast_status.json"
)

ROLLING_SCORECARD_FILE = (
    LIVE_DIR
    / "scorecard"
    / "rolling_scorecard.json"
)

FORECAST_HISTORY_FILE = (
    LIVE_DIR
    / "scorecard"
    / "forecast_history.json"
)

SYSTEM_STATUS_FILE = (
    LIVE_DIR
    / "scorecard"
    / "system_status.json"
)

VALIDATION_DIR = (
    LIVE_DIR
    / "validation"
)


# ---------------------------------------------------------------------
# Styling
# ---------------------------------------------------------------------

st.markdown(
    """
    <style>
    .block-container {
        max-width: 1400px;
        padding-top: 1.7rem;
        padding-bottom: 3rem;
    }

    .cc-hero {
        padding: 1.5rem 1.7rem;
        border-radius: 1rem;
        border: 1px solid #b9dfc5;
        background: linear-gradient(105deg, #e8f7ed, #f8fcf9);
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        margin-top: 0.6rem;
        margin-bottom: 1.3rem;
    }

    .cc-hero-label {
        color: #346247;
        font-size: 0.9rem;
        font-weight: 700;
        letter-spacing: 0.05rem;
        text-transform: uppercase;
        margin-bottom: 0.35rem;
    }

    .cc-hero-value {
        color: #173f27;
        font-size: 2.3rem;
        font-weight: 750;
        line-height: 1.15;
        margin-bottom: 0.45rem;
    }

    .cc-hero-note {
        color: #40564a;
        font-size: 0.93rem;
        line-height: 1.45;
    }

    .cc-card {
        min-height: 138px;
        padding: 1.05rem 1.15rem;
        border-radius: 0.85rem;
        border: 1px solid #e2e6e4;
        background: #ffffff;
        box-shadow: 0 1px 5px rgba(0,0,0,0.05);
    }

    .cc-card-green {
        border-left: 6px solid #2e8b57;
        background: #f1faf4;
    }

    .cc-card-blue {
        border-left: 6px solid #2f80ed;
        background: #f2f7ff;
    }

    .cc-card-amber {
        border-left: 6px solid #d89216;
        background: #fff9eb;
    }

    .cc-card-red {
        border-left: 6px solid #c0392b;
        background: #fff3f1;
    }

    .cc-card-grey {
        border-left: 6px solid #777777;
        background: #f7f7f7;
    }

    .cc-label {
        color: #59625d;
        font-size: 0.82rem;
        margin-bottom: 0.3rem;
    }

    .cc-value {
        color: #1f2937;
        font-size: 1.65rem;
        font-weight: 750;
        margin-bottom: 0.25rem;
        line-height: 1.15;
    }

    .cc-small {
        color: #59625d;
        font-size: 0.82rem;
        line-height: 1.35;
    }

    .cc-status {
        padding: 0.9rem 1.1rem;
        border-radius: 0.8rem;
        margin-bottom: 1rem;
    }

    .cc-status-healthy {
        background: #edf8f0;
        border: 1px solid #b9dfc5;
    }

    .cc-status-degraded {
        background: #fff8e8;
        border: 1px solid #eed28a;
    }

    .cc-status-unavailable {
        background: #fff0ee;
        border: 1px solid #e4b0aa;
    }

    .cc-section-note {
        color: #59625d;
        font-size: 0.9rem;
        margin-top: -0.4rem;
        margin-bottom: 1rem;
    }

    .cc-footer {
        color: #6a6a6a;
        font-size: 0.82rem;
        line-height: 1.45;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


# ---------------------------------------------------------------------
# Loading helpers
# ---------------------------------------------------------------------

@st.cache_data(ttl=300)
def load_json(path: Path) -> dict:
    if not path.exists():
        return {}

    try:
        with path.open(
            "r",
            encoding="utf-8",
        ) as file:
            return json.load(file)
    except Exception:
        return {}


@st.cache_data(ttl=300)
def load_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


def parse_datetime_series(
    series: pd.Series,
) -> pd.Series:
    parsed = pd.to_datetime(
        series,
        errors="coerce",
    )

    if parsed.dt.tz is None:
        parsed = parsed.dt.tz_localize(
            TZ_NAME,
            ambiguous="infer",
            nonexistent="shift_forward",
        )
    else:
        parsed = parsed.dt.tz_convert(
            TZ_NAME
        )

    return parsed


def latest_evaluation_date(
    scorecard: dict,
) -> str | None:
    """
    Return the latest completed evaluation date.

    Supports the field names used by different scorecard versions.
    """
    operational = scorecard.get(
        "operational_summary",
        {}
    )

    return (
        operational.get(
            "latest_evaluation_date"
        )
        or operational.get(
            "latest_evaluated_forecast_date"
        )
        or operational.get(
            "latest_evaluation"
        )
    )


def latest_evaluation_file(
    scorecard: dict,
    filename: str,
) -> Path | None:
    target_date = latest_evaluation_date(
        scorecard
    )

    if not target_date:
        return None

    path = (
        VALIDATION_DIR
        / target_date
        / filename
    )

    return path if path.exists() else None


# ---------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------

def fmt_intensity(value) -> str:
    if value is None or pd.isna(value):
        return "Not available"

    return f"{float(value):,.0f} gCO₂/kWh"


def fmt_kg(value) -> str:
    if value is None or pd.isna(value):
        return "Not available"

    return f"{float(value):,.2f} kg CO₂"


def fmt_percent(
    value,
    decimals: int = 1,
) -> str:
    if value is None or pd.isna(value):
        return "Not available"

    return f"{float(value):.{decimals}f}%"


def fmt_hours(value) -> str:
    if value is None or pd.isna(value):
        return "Not available"

    value = float(value)

    if abs(value - round(value)) < 0.05:
        number = int(round(value))
        unit = "hour" if number == 1 else "hours"
        return f"{number} {unit}"

    return f"{value:.1f} hours"


def fmt_datetime(
    value,
    date_only: bool = False,
) -> str:
    if not value:
        return "Not available"

    try:
        timestamp = pd.Timestamp(value)

        if timestamp.tzinfo is None:
            timestamp = timestamp.tz_localize(
                TZ_NAME
            )
        else:
            timestamp = timestamp.tz_convert(
                TZ_NAME
            )

        if date_only:
            return timestamp.strftime(
                "%A %-d %B %Y"
            )

        return timestamp.strftime(
            "%-d %b %Y, %-I:%M %p"
        )

    except Exception:
        return str(value)


def fmt_time(value) -> str:
    """
    Format a timestamp as Melbourne local time using a
    Windows-safe 12-hour clock format.
    """
    if not value:
        return "Not available"

    try:
        timestamp = pd.Timestamp(value)

        if timestamp.tzinfo is None:
            timestamp = timestamp.tz_localize(
                TZ_NAME
            )
        else:
            timestamp = timestamp.tz_convert(
                TZ_NAME
            )

        return timestamp.strftime(
            "%I:%M %p"
        ).lstrip("0")

    except Exception:
        return str(value)


def safe_mean(
    section: dict,
    metric: str,
):
    return (
        section
        .get(metric, {})
        .get("mean")
    )


def stars_text(stars) -> str:
    if stars is None or pd.isna(stars):
        return "Not yet available"

    count = int(round(float(stars)))
    count = max(0, min(5, count))

    return "★" * count + "☆" * (5 - count)


# ---------------------------------------------------------------------
# UI helpers
# ---------------------------------------------------------------------

def metric_card(
    label: str,
    value: str,
    note: str,
    style: str = "grey",
) -> None:
    st.markdown(
        f"""
        <div class="cc-card cc-card-{style}">
            <div class="cc-label">{label}</div>
            <div class="cc-value">{value}</div>
            <div class="cc-small">{note}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def system_status_banner(
    status: dict,
) -> None:
    health = str(
        status.get(
            "system_health",
            "unavailable",
        )
    ).lower()

    label = status.get(
        "system_health_label"
    )

    if not label:
        label = {
            "healthy": "Operating normally",
            "degraded": "Operational with warnings",
            "unavailable": "Service unavailable",
        }.get(
            health,
            "Status unavailable",
        )

    if health == "healthy":
        symbol = "🟢"
        css_class = "healthy"
    elif health == "degraded":
        symbol = "🟠"
        css_class = "degraded"
    else:
        symbol = "🔴"
        css_class = "unavailable"

    messages = status.get(
        "health_messages",
        []
    )

    if isinstance(messages, str):
        messages = [messages]

    notes = " ".join(
        str(message)
        for message in messages
        if message
    )

    if not notes:
        notes = (
            "Operational status is based on data freshness, "
            "successful updates and forecast publication."
        )

    st.markdown(
        f"""
        <div class="cc-status cc-status-{css_class}">
            <strong>{symbol} System status: {label}</strong><br>
            <span style="font-size:0.88rem; color:#555;">
                {notes}
            </span>
        </div>
        """,
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------------------
# Load backend outputs
# ---------------------------------------------------------------------

forecast = load_csv(
    FORECAST_FILE
)

recommendation = load_json(
    RECOMMENDATION_FILE
)

forecast_status = load_json(
    FORECAST_STATUS_FILE
)

rolling_scorecard = load_json(
    ROLLING_SCORECARD_FILE
)

forecast_history_raw = load_json(
    FORECAST_HISTORY_FILE
)

system_status = load_json(
    SYSTEM_STATUS_FILE
)

if isinstance(
    forecast_history_raw,
    list,
):
    forecast_history = pd.DataFrame(
        forecast_history_raw
    )

elif isinstance(
    forecast_history_raw,
    dict,
):
    forecast_history = pd.DataFrame(
        forecast_history_raw.get(
            "forecasts",
            [],
        )
    )

else:
    forecast_history = pd.DataFrame()

evaluation_summary_path = (
    latest_evaluation_file(
        rolling_scorecard,
        "evaluation_summary.json",
    )
)

scientific_comparison_path = (
    latest_evaluation_file(
        rolling_scorecard,
        "scientific_comparison.csv",
    )
)

latest_evaluation = (
    load_json(
        evaluation_summary_path
    )
    if evaluation_summary_path
    else {}
)

scientific_comparison = (
    load_csv(
        scientific_comparison_path
    )
    if scientific_comparison_path
    else pd.DataFrame()
)


# ---------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------

st.sidebar.title(
    "CleanCharge Live"
)

st.sidebar.caption(
    "Daily carbon-aware EV charging guidance for Victoria, Australia."
)

page = st.sidebar.radio(
    "Navigation",
    [
        "Today's forecast",
        "Forecast performance",
        "About",
    ],
)

st.sidebar.divider()

st.sidebar.markdown(
    """
    **Research basis**

    CleanCharge Live extends the methodology introduced in:

    Dia, H. (2026). *CleanCharge: Emissions-aware electric vehicle
    charging and infrastructure equity with open data in Melbourne.*

    *International Journal of Sustainable Transportation.*
    """
)

st.sidebar.markdown(
    "DOI: https://doi.org/10.1080/15568318.2026.2693676"
)


# ---------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------

st.title(
    "⚡ CleanCharge Live"
)

st.caption(
    "Daily carbon-aware electric vehicle charging guidance for "
    "Melbourne and Victoria"
)

system_status_banner(
    system_status
)


# ---------------------------------------------------------------------
# Page 1: Today's forecast
# ---------------------------------------------------------------------

if page == "Today's forecast":

    forecast_id = (
        recommendation.get("forecast_id")
        or forecast_status.get("forecast_id")
        or "Not available"
    )

    target_date = (
        recommendation.get("target_date")
        or forecast_status.get("target_date")
    )

    today_local = pd.Timestamp.now(
        tz=TZ_NAME
    ).normalize()

    target_timestamp = None

    if target_date:
        try:
            target_timestamp = pd.Timestamp(
                target_date
            ).tz_localize(
                TZ_NAME
            )
        except Exception:
            target_timestamp = None

    if (
        target_timestamp is not None
        and target_timestamp.date()
        != today_local.date()
    ):
        st.warning(
            "The displayed forecast is an archived development forecast "
            f"for {target_date}, not the current Melbourne date. "
            "Once daily automation is enabled, this page will update "
            "with the current official forecast."
        )

    best_start = recommendation.get(
        "best_window_start_local"
    )

    best_end = recommendation.get(
        "best_window_end_local"
    )

    if recommendation:

        need_kwh = recommendation.get(
            "need_kwh",
            20,
        )

        charger_kw = recommendation.get(
            "charger_kw",
            7,
        )

        duration_hours = recommendation.get(
            "exact_duration_hours"
        )

        if duration_hours is not None:
            total_minutes = int(
                round(
                    float(duration_hours) * 60
                )
            )

            duration_h = (
                total_minutes // 60
            )

            duration_m = (
                total_minutes % 60
            )

            duration_text = (
                f"{duration_h} h {duration_m} min"
            )
        else:
            duration_text = "Not available"

        st.markdown(
            f"""
            <div style="
                margin-bottom: 0.8rem;
                padding: 0.75rem 1rem;
                border-radius: 0.7rem;
                background: #f7f9fb;
                border: 1px solid #dfe5ea;
                color: #3f4a54;
                font-size: 0.92rem;
            ">
                <strong>Charging scenario:</strong>
                {need_kwh:g} kWh energy required
                &nbsp;|&nbsp;
                {charger_kw:g} kW charger
                &nbsp;|&nbsp;
                approximately {duration_text}
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown(
            f"""
            <div class="cc-hero">
                <div class="cc-hero-label">
                    Recommended Low-Carbon Charging Period
                </div>               
                <div class="cc-hero-value">
                    <span style="font-size:1.25rem;">
                        {pd.Timestamp(target_date).strftime("%A %d %B %Y")}
                    </span>
                    <br>
                    {fmt_time(best_start)} to {fmt_time(best_end)}
                </div>
                <div class="cc-hero-note">
                    Official forecast <strong>{forecast_id}</strong>
                    for {pd.Timestamp(target_date).strftime("%d %B %Y") if target_date else "the selected day"}.
                    This is the forecast period expected to provide
                    a low-carbon charging opportunity for the representative charging scenario.
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        c1, c2, c3, c4 = st.columns(4)

        with c1:
            metric_card(
                "Forecast period intensity",
                fmt_intensity(
                    recommendation.get(
                        "best_window_mean_intensity_g_per_kwh"
                    )
                ),
                "Mean forecast carbon intensity during the recommended period.",
                "green",
            )

        with c2:
            metric_card(
                "Estimated session emissions",
                fmt_kg(
                    recommendation.get(
                        "best_window_emissions_kg"
                    )
                ),
                (
                    f"For a {recommendation.get('need_kwh', 20):g} kWh "
                    f"session using a "
                    f"{recommendation.get('charger_kw', 7):g} kW charger."
                ),
                "blue",
            )

        with c3:
            metric_card(
                "Potential emissions saving",
                fmt_kg(
                    recommendation.get(
                        "emissions_saving_kg"
                    )
                ),
                "Compared with the highest-intensity charging window.",
                "green",
            )

        with c4:
            metric_card(
                "Relative saving",
                fmt_percent(
                    recommendation.get(
                        "emissions_saving_percent"
                    )
                ),
                "Forecast reduction relative to the highest-intensity window.",
                "amber",
            )

    else:
        st.error(
            "Today's recommendation file could not be loaded."
        )

    st.markdown("## Forecast timeline")

    st.markdown(
        """
        <div class="cc-section-note">
        Hourly forecast carbon intensity for the official Melbourne
        calendar-day forecast. The recommended charging window is shaded.
        </div>
        """,
        unsafe_allow_html=True,
    )

    if forecast.empty:
        st.warning(
            "Forecast data are not available."
        )

    elif {
        "local_time",
        "intensity_hat",
    }.issubset(
        forecast.columns
    ):
        chart_data = forecast.copy()

        chart_data["local_time"] = (
            parse_datetime_series(
                chart_data["local_time"]
            )
        )

        chart_data["intensity_hat"] = (
            pd.to_numeric(
                chart_data["intensity_hat"],
                errors="coerce",
            )
        )

        chart_data = chart_data.dropna(
            subset=[
                "local_time",
                "intensity_hat",
            ]
        )

        figure = go.Figure()

        figure.add_trace(
            go.Scatter(
                x=chart_data["local_time"],
                y=chart_data["intensity_hat"],
                mode="lines+markers",
                name="Forecast carbon intensity",
                line=dict(
                    color="#2e8b57",
                    width=3,
                ),
                marker=dict(
                    size=7,
                ),
                hovertemplate=(
                    "%{x|%I:%M %p}<br>"
                    "%{y:.0f} gCO₂/kWh"
                    "<extra></extra>"
                ),
            )
        )

        if best_start and best_end:
            try:
                window_start = pd.Timestamp(
                    best_start
                )

                window_end = pd.Timestamp(
                    best_end
                )

                figure.add_vrect(
                    x0=window_start,
                    x1=window_end,
                    fillcolor="#2e8b57",
                    opacity=0.17,
                    line_width=0,
                    annotation_text=(
                        "Recommended window"
                    ),
                    annotation_position="top left",
                )

            except Exception:
                pass

        now_local = pd.Timestamp.now(
            tz=TZ_NAME
        )

        if (
            not chart_data.empty
            and chart_data["local_time"].min()
            <= now_local
            <= chart_data["local_time"].max()
        ):


            figure.add_shape(
                type="line",
                x0=now_local,
                x1=now_local,
                y0=0,
                y1=1,
                xref="x",
                yref="paper",
                line=dict(
                    color="#555555",
                    dash="dash",
                ),
            )

            figure.add_annotation(
                x=now_local,
                y=1,
                xref="x",
                yref="paper",
                text="Now",
                showarrow=False,
                yshift=12,
            )         


        figure.update_layout(
            height=500,
            margin=dict(
                l=20,
                r=20,
                t=50,
                b=20,
            ),
            title=(
                "Forecast carbon intensity for Victoria's electricity supply"
            ),
            xaxis_title="Melbourne time",
            yaxis_title="Carbon intensity (gCO₂/kWh)",
            hovermode="x unified",
            legend=dict(
                orientation="h",
                yanchor="bottom",
                y=1.02,
                xanchor="left",
                x=0,
            ),
        )

        st.plotly_chart(
            figure,
            width="stretch",
        )

        st.caption(
            "Charging windows use start-inclusive, end-exclusive timing. "
            "For example, a 1:00 PM to 4:00 PM window includes the hourly "
            "intervals beginning at 1:00 PM, 2:00 PM and 3:00 PM. "
            "The 4:00 PM point represents the following hour and is not included."
        )

        window_hours = int(
            recommendation.get(
                "forecast_window_hours",
                3,
            )
        )

        candidate_rows = []

        if (
            window_hours >= 1
            and len(chart_data) >= window_hours
        ):
            selected_start = pd.Timestamp(
                best_start
            )

            if selected_start.tzinfo is None:
                selected_start = (
                    selected_start.tz_localize(
                        TZ_NAME
                    )
                )
            else:
                selected_start = (
                    selected_start.tz_convert(
                        TZ_NAME
                    )
                )

            for start_index in range(
                0,
                len(chart_data)
                - window_hours
                + 1,
            ):
                candidate_block = (
                    chart_data.iloc[
                        start_index:
                        start_index + window_hours
                    ]
                )

                candidate_start = (
                    candidate_block[
                        "local_time"
                    ].iloc[0]
                )

                candidate_end = (
                    candidate_block[
                        "local_time"
                    ].iloc[-1]
                    + pd.Timedelta(hours=1)
                )

                mean_intensity = float(
                    candidate_block[
                        "intensity_hat"
                    ].mean()
                )

                is_selected = bool(
                    candidate_start
                    == selected_start
                )

                included_hours = ", ".join(
                    fmt_time(value)
                    for value in candidate_block[
                        "local_time"
                    ]
                )

                candidate_rows.append(
                    {
                        "Optimal": (
                            "🟢"
                            if is_selected
                            else ""
                        ),
                        "Candidate window": (
                            f"{fmt_time(candidate_start)} "
                            f"to {fmt_time(candidate_end)}"
                        ),
                        "Included hourly starts": (
                            included_hours
                        ),
                        "Mean intensity (gCO₂/kWh)": (
                            round(
                                mean_intensity,
                                1,
                            )
                        ),
                    }
                )

        if candidate_rows:
            candidate_windows = pd.DataFrame(
                candidate_rows
            )

            selected_row = candidate_windows[
                candidate_windows[
                    "Optimal"
                ]
                == "🟢"
            ]

            if not selected_row.empty:
                selected_mean = selected_row[
                    "Mean intensity (gCO₂/kWh)"
                ].iloc[0]

                st.markdown(
                    f"""
                    **Why was this window selected?**  
                    Every possible {window_hours}-hour contiguous window
                    was evaluated. The selected window has the lowest
                    mean forecast carbon intensity,
                    **{selected_mean:,.1f} gCO₂/kWh**.
                    """
                )

            with st.expander(
                "View all candidate charging windows"
            ):
                candidate_windows[
                    "Mean intensity (gCO₂/kWh)"
                ] = candidate_windows[
                    "Mean intensity (gCO₂/kWh)"
                ].map(
                    lambda x: f"{float(x):.1f}"
                )                    
                st.dataframe(
                    candidate_windows,
                    width="stretch",
                    hide_index=True,
                )

    else:
        st.error(
            "The forecast file does not contain the expected "
            "`local_time` and `intensity_hat` columns."
        )

    # st.markdown("## How did the latest evaluated forecast perform?")
    
    evaluation_date_text = latest_evaluation_date(
        rolling_scorecard
    )

    if evaluation_date_text:
        report_date = pd.Timestamp(
            evaluation_date_text
        )

        st.markdown(
            f"## System Performance Over Time"
            f"({report_date.strftime('%d %B %Y')})"
        )

        st.caption(
            f"These results evaluate the official forecast issued for "
            f"{report_date.strftime('%d %B %Y')} after the actual hourly "
            "electricity observations became available."
        )

    else:
        st.markdown(
            "## System Performance Over Time"
        )

        st.caption(
            "No completed forecast evaluation is available yet."
        )

    
    if latest_evaluation:
        c1, c2, c3, c4 = st.columns(4)

        with c1:
            metric_card(
                "Recommendation Quality",
                (
                    f"{stars_text(latest_evaluation.get('stars'))}"
                ),
                (
                    f"{latest_evaluation.get('grade', 'n/a')} | "
                    f"{latest_evaluation.get('decision_quality_label', 'Not available')}"
                ),
                "green",
            )

        with c2:
            metric_card(
                "Carbon Savings Capture",
                fmt_percent(
                    latest_evaluation.get(
                        "carbon_savings_capture_percent"
                    )
                ),
                "Share of the maximum possible carbon saving captured.",
                "green",
            )

        with c3:
            metric_card(
                "Window timing error",
                fmt_hours(
                    latest_evaluation.get(
                        "timing_error_hours"
                    )
                ),
                "Difference between the published and actual cleanest start times.",
                "blue",
            )

        with c4:
            metric_card(
                "Scientific MAE",
                fmt_intensity(
                    latest_evaluation.get(
                        "scientific_mae_g_per_kwh"
                    )
                ),
                "Mean absolute hourly forecast error.",
                "amber",
            )

        st.caption(
            "Recommendation quality and scientific accuracy are reported "
            "separately. A forecast may overestimate absolute carbon "
            "intensity while still identifying a useful charging window."
        )

    else:
        st.info(
            "No completed evaluation summary is available yet."
        )


# ---------------------------------------------------------------------
# Page 2: Forecast performance
# ---------------------------------------------------------------------

elif page == "Forecast performance":

    st.header(
        "Performance evaluation"
    )
    
    st.caption(
        "Transparent evaluation of scientific forecast accuracy, "
        "recommendation performance and environmental outcomes."
    )

    operational = rolling_scorecard.get(
        "operational_summary",
        {}
    )

    scientific = rolling_scorecard.get(
        "scientific_performance",
        {}
    )

    decision = rolling_scorecard.get(
        "decision_performance",
        {}
    )

    c1, c2, c3, c4 = st.columns(4)

    with c1:
        metric_card(
            "Forecasts evaluated",
            str(
                operational.get(
                    "forecasts_evaluated",
                    0,
                )
            ),
            "Official daily forecasts with complete evaluation records.",
            "blue",
        )

    with c2:
        metric_card(
            "Average Carbon Savings Capture",
            fmt_percent(
                safe_mean(
                    decision,
                    "carbon_savings_capture_percent",
                )
            ),
            "Average share of maximum possible carbon saving captured.",
            "green",
        )

    with c3:
        metric_card(
            "Average timing error",
            fmt_hours(
                safe_mean(
                    decision,
                    "timing_error_hours",
                )
            ),
            "Average difference between the recommended and actual lowest-carbon charging periods.",
            "blue",            
        )

    with c4:
        metric_card(
            "Average scientific MAE",
            fmt_intensity(
                safe_mean(
                    scientific,
                    "mae_g_per_kwh",
                )
            ),
            "Average hourly mean absolute forecast error.",
            "amber",
        )

    st.markdown("## Latest forecast report card")

    if latest_evaluation:
        report_left, report_right = (
            st.columns([1, 1])
        )

        overlap_hours = latest_evaluation.get(
            "window_overlap_hours"
        )

        evaluation_window_hours = latest_evaluation.get(
            "evaluation_window_hours"
        )

        if (
            overlap_hours is not None
            and evaluation_window_hours is not None
        ):
            overlap_hours_number = float(
                overlap_hours
            )

            window_hours_number = float(
                evaluation_window_hours
            )

            overlap_display = (
                int(overlap_hours_number)
                if overlap_hours_number.is_integer()
                else overlap_hours_number
            )

            window_display = (
                int(window_hours_number)
                if window_hours_number.is_integer()
                else window_hours_number
            )

            overlap_note = (
                f"{overlap_display} of the "
                f"{window_display} recommended charging hours "
                "overlapped the actual lowest-carbon period."
            )
            
        else:
            overlap_note = (                
                "Overlap between the recommended and actual lowest-carbon charging periods."
            )

        with report_left:
            st.markdown(
                f"""
                **Forecast date:**  
                {pd.Timestamp(latest_evaluation.get('target_date')).strftime('%d %B %Y')}

                **Recommendation quality:**  
                {stars_text(latest_evaluation.get('stars'))}  
                {latest_evaluation.get('grade', '')} | {latest_evaluation.get('decision_quality_label', '')}        

                **Carbon Savings Capture:**  
                {fmt_percent(latest_evaluation.get('carbon_savings_capture_percent'))}  
                Captured {fmt_percent(latest_evaluation.get('carbon_savings_capture_percent'), decimals=0)} of the maximum possible emissions saving.

                **Timing error:**  
                {fmt_hours(latest_evaluation.get('timing_error_hours'))}  
                Difference between the recommended and actual lowest-carbon charging periods.

                **Window overlap:**  
                {fmt_percent(latest_evaluation.get('window_overlap_percent'))}  
                {overlap_note}

                **Forecast identifier:**  
                `{latest_evaluation.get('forecast_id', 'Not available')}`                
                """
            )
    

        with report_right:
            st.markdown(
                f"""                

                **Scientific MAE:**  
                {fmt_intensity(latest_evaluation.get('scientific_mae_g_per_kwh'))}: Average absolute difference between published & observed hourly intensity.

                **Scientific RMSE:**  
                {fmt_intensity(latest_evaluation.get('scientific_rmse_g_per_kwh'))}

                **Scientific sMAPE:**  
                {fmt_percent(latest_evaluation.get('scientific_smape_percent'))}

                **Scientific R²:**  
                {latest_evaluation.get('scientific_r2', 0):.2f}

                **Data completeness:**  
                {fmt_percent(latest_evaluation.get('data_completeness_percent'))}
                """
            )

    if not scientific_comparison.empty:
        required = {
            "local_time",
            "intensity_hat",
            "intensity_actual",
        }

        if required.issubset(
            scientific_comparison.columns
        ):
            comparison = (
                scientific_comparison.copy()
            )

            comparison["local_time"] = (
                parse_datetime_series(
                    comparison["local_time"]
                )
            )

            comparison["intensity_hat"] = (
                pd.to_numeric(
                    comparison["intensity_hat"],
                    errors="coerce",
                )
            )

            comparison[
                "intensity_actual"
            ] = pd.to_numeric(
                comparison[
                    "intensity_actual"
                ],
                errors="coerce",
            )

            comparison = comparison.dropna(
                subset=[
                    "local_time",
                    "intensity_hat",
                    "intensity_actual",
                ]
            )

            figure = go.Figure()

            figure.add_trace(
                go.Scatter(
                    x=comparison["local_time"],
                    y=comparison["intensity_actual"],
                    mode="lines+markers",
                    name="Actual",
                    line=dict(
                        width=3,
                    ),
                )
            )

            figure.add_trace(
                go.Scatter(
                    x=comparison["local_time"],
                    y=comparison["intensity_hat"],
                    mode="lines+markers",
                    name="Forecast",
                    line=dict(
                        width=3,
                        dash="dash",
                    ),
                )
            )

            figure.update_layout(
                title=(
                    "Published forecast versus observed carbon intensity"
                ),
                xaxis_title="Melbourne time",
                yaxis_title=(
                    "Carbon intensity (gCO₂/kWh)"
                ),
                height=460,
                hovermode="x unified",
            )

            st.plotly_chart(
                figure,
                width="stretch",
            )

    st.markdown("## System Performance Over Time")

    st.caption(
        "Rolling performance statistics based on all completed "
        "forecast evaluations."
    )

    if forecast_history.empty:
        st.info(
            "Performance trends will appear after additional daily "
            "forecasts have been evaluated."
        )

    elif "target_date" in forecast_history.columns:
        history = forecast_history.copy()

        history["target_date"] = (
            pd.to_datetime(
                history["target_date"],
                errors="coerce",
            )
        )

        history = history.dropna(
            subset=["target_date"]
        )

        if (
            "carbon_savings_capture_percent"
            in history.columns
        ):
            figure = go.Figure()

            figure.add_trace(
                go.Scatter(
                    x=history["target_date"],
                    y=history[
                        "carbon_savings_capture_percent"
                    ],
                    mode="lines+markers",
                    name="Carbon Savings Capture",
                )
            )

            figure.update_layout(
                title=(
                    "Carbon Savings Capture over time"
                ),
                xaxis_title="Forecast date",
                yaxis_title="Carbon Savings Capture (%)",
                height=420,
            )

            st.plotly_chart(
                figure,
                width="stretch",
            )

        with st.expander(
            "View forecast history table"
        ):
            st.dataframe(
                history,
                width="stretch",
                hide_index=True,
            )


# ---------------------------------------------------------------------
# Page 3: About
# ---------------------------------------------------------------------

else:

    st.header(
        "About CleanCharge Live"
    )

    st.markdown(
        """
        **CleanCharge Live** is an open, transparent operational
        forecasting service for emissions-aware electric vehicle
        charging in Victoria, Australia.

        It extends the methodology developed in the peer-reviewed
        CleanCharge study and publishes one official forecast for each
        Melbourne calendar day.
        """
    )

    st.markdown("## How it works")

    st.markdown(
        """
        1. Victoria-region electricity observations are retrieved from
           OpenElectricity.

        2. A rolling 90-day hourly history is maintained.

        3. The forecasting model is retrained using information available
           before the target day begins.

        4. A midnight-to-midnight carbon-intensity forecast is published
           and assigned a permanent forecast identifier.

        5. The forecast is archived without being overwritten.

        6. Once actual observations become available, the forecast is
           evaluated scientifically and operationally.

        7. Rolling performance statistics are published transparently.
        """
    )


    st.markdown("## Why two kinds of evaluation")

    st.markdown(
        """
        CleanCharge Live evaluates forecast performance in two complementary
        ways.

        **Scientific forecast accuracy** measures how closely the forecast
        hourly carbon-intensity values match the actual observations. These
        metrics include MAE, RMSE, sMAPE, R² and bias, and are commonly used
        to assess forecasting models.

        **Recommendation quality** measures how useful the published
        low-carbon charging recommendation was in practice. These metrics
        include timing error, overlap with the actual lowest-carbon period,
        and Carbon Savings Capture.

        The two evaluations answer different questions.

        - **Scientific forecast accuracy:** *How accurately did the model predict carbon intensity?*
        - **Recommendation quality:** *How useful was the published charging recommendation?*

        These measures are reported separately because a forecast does not
        need to predict every hourly value perfectly to provide a highly
        effective low-carbon charging recommendation.
        """
    )



    st.markdown("## Carbon Savings Capture")

    st.markdown(
        """
        Carbon Savings Capture measures how much of the maximum possible
        emissions reduction was achieved by following the published
        recommendation.

        It compares the emissions saving from the recommended charging
        period with the maximum saving that could have been achieved using
        perfect hindsight after the day has finished.

        - **100%** indicates that the recommendation achieved the maximum
          possible emissions reduction.
        - **90%** indicates that it captured 90% of the maximum available
          reduction.
        - Lower values indicate that part of the available opportunity
          was missed.

        This metric reflects the practical value of the recommendation,
        while the scientific forecasting metrics describe the accuracy of
        the underlying forecast itself.
        """
    )    
    

    st.markdown("## Research reference")

    st.markdown(
        """
        Dia, H. (2026). *CleanCharge: Emissions-aware electric vehicle
        charging and infrastructure equity with open data in Melbourne.*
        *International Journal of Sustainable Transportation*, 1–27.

        DOI: https://doi.org/10.1080/15568318.2026.2693676
        """
    )

    st.markdown("## Important limitations")

    st.markdown(
        """
        - CleanCharge Live is a research and demonstration service.
        - Forecasts are subject to uncertainty.
        - The current implementation represents Victoria-region
          electricity conditions.
        - It does not account for household-specific tariffs, rooftop
          solar, battery storage or network constraints.
        - It should not be interpreted as guaranteed operational advice.
        """
    )


# ---------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------

st.divider()

st.markdown(
    """
    <div class="cc-footer">
    CleanCharge Live is an open research prototype developed to support
    transparent and reproducible analysis of emissions-aware EV charging.
    Electricity data are derived from OpenElectricity/OpenNEM.
    Forecast performance is evaluated against subsequently observed data.
    </div>
    """,
    unsafe_allow_html=True,
)